language: java
deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    app: $APP_NAME
    env: $ENV_NAME
    bucket_name: $BUCKET_NAME
    region: $REGION
    access-key-id: $ACCESS_KEY_ID
    secret-access-key: $SECRET_ACCESS_KEY
    zip_file: target/upload-1.0.zip
    on:
      all_branches: true
